config/routes.rb
Rails.application.routes.draw do
  resources :request_records
  get 'static_pages/index'

  post 'request_records/passage/audi', to: 'request_records#create'
  get 'request_records/passage/audi', to: 'request_records#passage_audi'

  post 'request_records/passage/bmw2', to: 'request_records#create'
  get 'request_records/passage/bmw2', to: 'request_records#passage_bmw'

  post 'request_records/passage/bmw', to: 'request_records#create'
  get 'request_records/passage/bmw', to: 'request_records#passage_second'

  post 'request_records/passage/levante', to: 'request_records#create'
  get 'request_records/passage/levante', to: 'request_records#passage'

  post 'request_records/passage/benz_25102018', to: 'request_records#create'
  get 'request_records/passage/benz_25102018', to: 'request_records#passage_benz_25102018'

  post 'request_records/passage/toyota_25102018', to: 'request_records#create'
  get 'request_records/passage/toyota_25102018', to: 'request_records#passage_toyota_25102018'

  get 'fihiauhefouygaouywefiasafawefsduaf', to: 'request_records#my_success', as: "my_success"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  validates :phone, format: { with: /\A04\d{8}\z/ }
  self.abstract_class = true
end

app/models/request_record.rb
class RequestRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/request_records_controller.rb
require 'csv'
class RequestRecordsController < ApplicationController
  before_action :set_request_record, only: [:show, :edit, :update, :destroy]

  # GET /request_records
  # GET /request_records.json
  def index
    csv_text = File.read(Rails.root + "brand.csv")
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
      puts "__________"
      puts row
      puts row.values_at(0).class
      puts row.values_at(1).first.class
    end
    @request_records = RequestRecord.all
  end

  # GET /request_records/1
  # GET /request_records/1.json
  def show
  end

  # GET /request_records/new
  def new
    @request_record = RequestRecord.new
  end

  # GET /request_records/1/edit
  def edit
  end

  def my_success

  end

  def passage
    @request_record = RequestRecord.new
  end

  def passage_second
    @request_record = RequestRecord.new
  end

  def passage_bmw
    @request_record = RequestRecord.new
  end

  def passage_audi
    @request_record = RequestRecord.new
  end

  def passage_benz_25102018
    @request_record = RequestRecord.new
  end

  def passage_toyota_25102018
    @request_record = RequestRecord.new
  end


  # POST /request_records
  # POST /request_records.json
  def create
      @request_record = RequestRecord.new
      @request_record.firstName = params[:firstName]
      @request_record.lastName = params[:lastName]
      if params[:location] == "1"
        @request_record.location = "悉尼"
      else
        @request_record.location = "墨尔本"
      end

      brand = params[:brand]
      model = params[:model]
      csv_text = File.read(Rails.root + "brand.csv")
      csv = CSV.parse(csv_text, :headers => true)
      csv.each do |row|
        if row.values_at(0).first == brand
          @request_record.brand = row.values_at(1).first
        end

        if row.values_at(0).first == model
          @request_record.model = row.values_at(1).first
        end
      end

      @request_record.phone = "0400000000"

      if params[:request_type] == "0"
        @request_record.request_type = "询问优惠"
      else
        @request_record.request_type = "预约试驾"
      end

      if @request_record.save
        redirect_to edit_request_record_path(@request_record.id)
      end
  end

  # PATCH/PUT /request_records/1
  # PATCH/PUT /request_records/1.json
  def update
    respond_to do |format|
      if @request_record.update(request_record_params)
        format.html { redirect_to my_success_path, notice: 'Request record was successfully updated.' }
        # format.json { render :show, status: :ok, location: @request_record }
      else
        format.html { render :edit }
        format.json { render json: @request_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_records/1
  # DELETE /request_records/1.json
  def destroy
    @request_record.destroy
    respond_to do |format|
      format.html { redirect_to request_records_url, notice: 'Request record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_record
      @request_record = RequestRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_record_params
      params.require(:request_record).permit(:firstName, :lastName, :location, :request_type, :brand, :model, :phone)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/request_records_helper.rb
module RequestRecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
        <meta content="IE=edge" http-equiv="X-UA-Compatible">
            <meta content="width=device-width, initial-scale=1" name="viewport">
                <title>
                    查查车APP-查车型查销售，就用查查车！
                </title>
                <link href=<%= asset_path 'animate.css' %> rel="stylesheet">
                    <link href=<%= asset_path 'bootstrap.min.css' %> rel="stylesheet">
                        <link href=<%= asset_path 'style.css' %> rel="stylesheet">
                            <link href=<%= asset_path 'fonts.css' %> rel="stylesheet">
                                <script src=<%= asset_path 'jquery.min.js' %>>
                                </script>
                                <script src=<%= asset_path 'bootstrap.min.js' %>>
                                </script>
                                <script src=<%= asset_path 'modernizr.custom.37797.js' %>>
                                </script>
                            </link>
                        </link>
                    </link>
                </link>
            </meta>
        </meta>
    </meta>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Google Tag Manager -->
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5S67VGH');
    </script>
    <!-- End Google Tag Manager -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/request_records/_form.html.erb
<%= form_with(model: request_record, local: true) do |form| %>
  <% if request_record.errors.any? %>
    <div id="error_explanation" style="margin: auto; width: 85%" >
      <!-- <h2><%= pluralize(request_record.errors.count, "error") %> prohibited this request_record from being saved:</h2> -->
      <h2 style="font-size: 11pt">请输入04开头的澳洲手机号码</h2>
      <!-- <ul>
      <% request_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul> -->
    </div>
  <% end %>
<!--
  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :request_type %>
    <%= form.text_field :request_type %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div> -->

  <div class="container" style="height:100%;width:100%;">
          <div class="flexbox" style="height:300px;">
              <div class="col-md-12">
                  <h2 id="myModalLabel">
                      您的电话
                  </h2>
              </div>
              <div class="col-md-12">
                  <div class="form-group">
                    <input class="form-control" type="text" name="request_record[phone]" id="request_record_phone" />
                  </div>
              </div>
              <div class="col-md-12">
                  <h3>
                      *我们需要您的电话为您提供优惠信息
                  </h3>
              </div>
              <div class="modal-footer">
                  <input class="btn-outline complete" name="commit" type="submit" value="完成申请" style="margin-bottom: 30px; margin-top: 0px !important;"/>
              </div>
          </div>
      </form>
  </div>




<!-- <input id="phone" name="phone" type="text" /> -->
  <!-- <div class="field">
    <%= form.text_field :phone %>
  </div> -->




<% end %>

app/views/request_records/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
    询价与试驾
  </title>
  <link href=<%= asset_path 'bootstrap.min.css' %> rel="stylesheet"/>
  <link href=<%= asset_path 'normalize.css' %> rel="stylesheet"/>
  <link href=<%= asset_path 'style2.css' %> rel="stylesheet"/>
  <link href="//cdn.bootcss.com/tether/1.3.6/css/tether.min.css" rel="stylesheet">
  <script src="//cdn.bootcss.com/tether/1.3.6/js/tether.min.js">
  </script>
  <script src=<%= asset_path 'jquery.min.js' %>>
  </script>
  <script src=<%= asset_path 'bootstrap.min.js' %>>
  </script>
  <script src=<%= asset_path 'brand.js' %>>
  </script>
  <script src=<%= asset_path 'form.js' %>>
  </script>
</link>
<!-- Google Tag Manager -->
<script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5S67VGH');
</script>
<!-- End Google Tag Manager -->
</head>
<body>
  <noscript>
    <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-5S67VGH" style="display:none;visibility:hidden" width="0">
    </iframe>
  </noscript>
  <%= render 'form', request_record: @request_record %>

  <!-- <%= link_to 'Show', @request_record %> |
  <%= link_to 'Back', request_records_path %> -->
</body>
</html>

app/views/request_records/index.html.erb
<DOCTYPE! html>
<html>
<body>
<p id="notice"><%= notice %></p>

<h1>Request Records</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Location</th>
      <th>Request type</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Phone</th>
      <th>时间</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_records.each do |request_record| %>
      <tr>
        <td><%= request_record.firstName %></td>
        <td><%= request_record.lastName %></td>
        <td><%= request_record.location %></td>
        <td><%= request_record.request_type %></td>
        <td><%= request_record.brand %></td>
        <td><%= request_record.model %></td>
        <td><%= request_record.phone %></td>
        <td><%= request_record.created_at.to_date %></td>
        <!-- <td><%= link_to 'Show', request_record %></td>
        <td><%= link_to 'Edit', edit_request_record_path(request_record) %></td> -->
        <td><%= link_to 'Destroy', request_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Record', new_request_record_path %>
</body>
</html>

app/views/request_records/my_success.html.erb
        <!-- Google Tag Manager (noscript) -->
        <noscript>
            <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-5S67VGH" style="display:none;visibility:hidden" width="0">
            </iframe>
        </noscript>
        <!-- End Google Tag Manager (noscript) -->
        <div class="container-fluid">
            <div class="success">
                <h1>
                    <span id="request_type">
                        您的信息已收到
                    </span>
                    ，我们会尽快联系您
                </h1>
            </div>
        </div>

app/views/request_records/new.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <title>
            询价与试驾
        </title>
        <link href=<%= asset_path 'bootstrap.min.css' %> rel="stylesheet"/>
        <link href=<%= asset_path 'normalize.css' %> rel="stylesheet"/>
        <link href=<%= asset_path 'style2.css' %> rel="stylesheet"/>
        <link href="//cdn.bootcss.com/tether/1.3.6/css/tether.min.css" rel="stylesheet">
            <script src="//cdn.bootcss.com/tether/1.3.6/js/tether.min.js">
            </script>
            <script src=<%= asset_path 'jquery.min.js' %>>
            </script>
            <script src=<%= asset_path 'bootstrap.min.js' %>>
            </script>
            <script src=<%= asset_path 'brand.js' %>>
            </script>
            <script src=<%= asset_path 'form.js' %>>
            </script>
        </link>
        <!-- Google Tag Manager -->
        <script>
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5S67VGH');
        </script>
        <!-- End Google Tag Manager -->
    </head>
    <body>
        <!-- Google Tag Manager (noscript) -->
        <noscript>
            <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-5S67VGH" style="display:none;visibility:hidden" width="0">
            </iframe>
        </noscript>
        <!-- End Google Tag Manager (noscript) -->
        <%= form_with(model: @request_record, local: true, id: 'form') do |form| %>
            <input id="request_type" name="request_type" type="hidden"/>
            <input id="location" name="location" type="hidden"/>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            立刻咨询或预约试驾
                        </h1>
                    </div>
                </div>
                <div class="row">
                    <form>
                        <div class="col-6">
                            <h2>
                                姓
                            </h2>
                            <div class="form-group">
                                <input class="form-control" id="lastName" name="lastName" type="text"/>
                            </div>
                        </div>
                        <div class="col-6">
                            <h2>
                                名
                            </h2>
                            <div class="form-group">
                                <input class="form-control" id="firstName" name="firstName" type="text"/>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h2>
                            您想
                        </h2>
                    </div>
                </div>
                <div class="row request_type-row">
                    <div class="btn-item">
                        <button class="btn" onclick="setRadio(this, request_type)" style="text-align: left;" type="button" value="0">
                            询问优惠
                        </button>
                    </div>
                    <div class="btn-item">
                        <button class="btn" onclick="setRadio(this, request_type)" style="text-align: left;" type="button" value="1">
                            预约试驾
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h2>
                            您在
                        </h2>
                    </div>
                </div>
                <div class="row location-row">
                    <div class="btn-item">
                        <button class="btn" onclick="setRadio(this, location)" style="text-align: left;" type="button" value="0">
                            墨尔本
                        </button>
                    </div>
                    <div class="btn-item">
                        <button class="btn" onclick="setRadio(this, location)" style="text-align: left;" type="button" value="1">
                            悉尼
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h2>
                            品牌/车型
                        </h2>
                    </div>
                </div>
                <div class="row">
                    <div class="btn-item">
                        <select class="option" id="brand" name="brand">
                            <option>
                                品牌
                            </option>
                        </select>
                    </div>
                    <div class="btn-item">
                        <select class="option" id="model" name="model">
                            <!--Below shows when '1 column' is selected is hidden otherwise-->
                            <option>
                                车型
                            </option>
                        </select>
                    </div>
                </div>

                <div class="row">
                  <button class="btn-outline">
                         提交
                  </button>
                <!--     <button class="btn-outline" data-toggle="modal" href="#modal-container-264992">
                        提交
                    </button>
                    <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="modal-container-264992" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button class="close" data-dismiss="modal" type="button">
                                        <span aria-hidden="true">
                                            ×
                                        </span>
                                    </button>
                                </div>

                                <div class="modal-footer">
                                  <div class="actions">
                                    <%= form.submit %>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
        <% end %>
        <!-- <script>
            $("select").click(function(){
                $(this).css({"background-color": "#EA2E36", "color": "#fff"});
            });
        </script>
        <script type="text/javascript">
            window.addEventListener('keydown',function(e){if(e.keyIdentifier=='U+000A'||e.keyIdentifier=='Enter'||e.keyCode==13){if(e.target.nodeName=='INPUT'&&e.target.type=='text'){e.preventDefault();return false;}}},true);
        </script> -->
    </body>
</html>

app/views/request_records/passage_audi.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
    询价与试驾
  </title>
  <link href=<%= asset_path 'bootstrap.min.css' %> rel="stylesheet"/>
  <link href=<%= asset_path 'normalize.css' %> rel="stylesheet"/>
  <link href=<%= asset_path 'style2.css' %> rel="stylesheet"/>
  <link href="//cdn.bootcss.com/tether/1.3.6/css/tether.min.css" rel="stylesheet">
  <script src="//cdn.bootcss.com/tether/1.3.6/js/tether.min.js">
  </script>
  <script src=<%= asset_path 'jquery.min.js' %>>
  </script>
  <script src=<%= asset_path 'bootstrap.min.js' %>>
  </script>
  <script src=<%= asset_path 'brand.js' %>>
  </script>
  <script src=<%= asset_path 'form.js' %>>
  </script>
</link>
<!-- Google Tag Manager -->
<script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5S67VGH');
</script>

<style>
h1, h2, h3, h4 {
  font-family: "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei";
}
p {
  line-height: 1.7;
  margin: 0 0 1em;
}
.flex-column {
  -ms-flex-direction: column!important;
  flex-direction: column!important;
}
.article {
  margin-left: 10pt;
  margin-right: 10pt;
  text-align: left;
  font-weight: 400;
}
.article p {
  font-size: 0.95em;
}
.article h1 {
  font-weight: 600;
  font-size: 25pt;
  margin: 10px 0;
}
.label-kicker {
  font-weight: 800;
  display: inline-block;
  text-transform: uppercase;
  color: #fff;
  background: #1c1c1c;
  font-size: 13px;
  padding: 2px 4px 2px 3px;
  line-height: 1;
  letter-spacing: 1px;
  margin: 0 0 2px;
}
.byline {
  color: #737373;
  margin-bottom: .5em;
  font-size: 0.9em;
}
.bold {
  font-weight: 800;
}
.photo {
  margin: 20px 0;
}
.full {
  clear: both;
}
.list h1 {
  font-size: 1em;
  font-weight: normal;
}
.article ul {
  list-style-type: disc;
}
.article ul li {
  background: none;
  padding-left: 6px;
  font-size: 0.8em;
  color: grey;
  line-height: 2;
  font-weight: normal;
}
.underline {
  border-bottom: 1px solid #EDEDED;
  margin: 20px 0;
}

.list {
  font-size: 11pt
}
</style>
</head>


<body>


  <!-- Google Tag Manager (noscript) -->
  <noscript>
    <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-5S67VGH" style="display:none;visibility:hidden" width="0">
    </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->

  <div class="container">
  <div class="row">
    <div class="col">
      <img alt="banner" src=<%= asset_path 'audi_banner.jpg' %>/>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <img alt="a1" src=<%= asset_path 'audi_1.jpg' %>/>
    </div>
    <div class="col-sm">
      <img alt="a2" src=<%= asset_path 'audi_2.jpg' %>/>
    </div>
    <div class="col-sm">
      <img alt="a3" src=<%= asset_path 'audi_3.jpg' %>/>
    </div>
  </div>
</div>

  <br/>

  <%= form_with(model: @request_record, local: true, id: 'form') do |form| %>
  <input id="request_type" name="request_type" type="hidden"/>
  <input id="location" name="location" type="hidden"/>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <h1>
          立刻咨询或预约试驾
        </h1>
      </div>
    </div>
    <div class="row">
      <form>
        <div class="col-6">
          <h2>
            姓
          </h2>
          <div class="form-group">
            <input class="form-control" id="lastName" name="lastName" type="text"/>
          </div>
        </div>
        <div class="col-6">
          <h2>
            名
          </h2>
          <div class="form-group">
            <input class="form-control" id="firstName" name="firstName" type="text"/>
          </div>
        </div>
      </form>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2>
          您想
        </h2>
      </div>
    </div>
    <div class="row request_type-row">
      <div class="btn-item">
        <button class="btn" onclick="setRadio(this, request_type)" style="text-align: left;" type="button" value="0">
          询问优惠
        </button>
      </div>
      <div class="btn-item">
        <button class="btn" onclick="setRadio(this, request_type)" style="text-align: left;" type="button" value="1">
          预约试驾
        </button>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2>
          您在
        </h2>
      </div>
    </div>
    <div class="row location-row">
      <div class="btn-item">
        <button class="btn" onclick="setRadio(this, location)" style="text-align: left;" type="button" value="0">
          墨尔本
        </button>
      </div>
      <div class="btn-item">
        <button class="btn" onclick="setRadio(this, location)" style="text-align: left;" type="button" value="1">
          悉尼
        </button>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2>
          品牌/车型
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="btn-item">
        <select class="option" id="brand" name="brand">
          <option>
            品牌
          </option>
        </select>
      </div>
      <div class="btn-item">
        <select class="option" id="model" name="model">
          <!--Below shows when '1 column' is selected is hidden otherwise-->
          <option>
            车型
          </option>
        </select>
      </div>
    </div>

    <div class="row">
      <button class="btn-outline">
        提交
      </button>
    </div>
  </div>
  <% end %>
  <br/>
  <br/>
  <br/>

</body>
</html>

app/views/request_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @request_record.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @request_record.lastName %>
</p>

<p>
  <strong>Location:</strong>
  <%= @request_record.location %>
</p>

<p>
  <strong>Request type:</strong>
  <%= @request_record.request_type %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @request_record.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @request_record.model %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @request_record.phone %>
</p>

<p>
  <strong>时间:</strong>
  <%= @request_record.created_at %>
</p>

<%= link_to 'Edit', edit_request_record_path(@request_record) %> |
<%= link_to 'Back', request_records_path %>